### ISSUE TITLE
Develop Date Picker Component from AO Example

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-prototype-kit#15]
The Architecture team has developed a working example of a Date Picker that needs to have FSA Style applied to the component.

- [x] Install AO Version using PKit
- [x] Get working localy
- [ ] Applied FSA CSS using appropriate SCSS
- [ ] Peer Review
- [ ] Integrate into FSA Style Codebase

FSA-Style Codebase Tasks:
- [ ] Ensure it works sans-Webpack (tech stack-agnostic)

**Comment by bignamehere** [comment]
@francisrupert I have committed the current branch for you to go over.

77c4982

**Comment by francisrupert** [comment]
Casey (@bignamehere), Aaron (@atdiff), and Adi (@arosenblum),

I've started to dive into the Date Picker you’ve been working with so I can understand the overall implications to `fsa-style`. In particular, because this would be the first Design System component to include **Production**-quality JS, this task isn’t something we do lightly. A few questions:

### Source

Can you point to the direct source and version of the you’ve used? I know it comes from **assets.cms.gov**, however I’ve seen references to different versions and want to make sure. For example there’s...

https://assets.cms.gov/resources/framework/2.0/Pages/datepicker.html 
vs
https://assets.cms.gov/resources/framework/3.4.1/Pages/#datepicker

### Webpackery

I understand you’ve created a Webpack-wrapped version. Since the Design System must be **tech stack-agnostic**, I want to make sure it will work without. 

My first stab at doing so this morning ([using this source](https://assets.cms.gov/resources/framework/3.4.1/Pages/#datepicker)) was easy enough and I got it working -- viewable at [this Sharepoint location](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/XCut%20-%20UX/8.%20Projects/fsa-style/branches/experimental/date-picker.html).

### Next Steps

Once I feel good about the direction we've got going with your responses to the above, I'll coordinate with Casey to plan out its inclusion in `fsa-style`'s next release.

**Comment by AdiRosenblum-USDA** [comment]
@francisrupert The way I read some of this message makes me think we may have 2 efforts going on at once now.  

1. Provide a standalone, fsa-style enabled, 508 accessible datepicker that dev teams can use outside of SPA development (in legacy apps)
2) Integrate this into fsa-style as a provided component in the design system

Are you referencing work towards #2?

**Comment by AaronDiffenderfer-USDA** [comment]
@francisrupert, we used version 2.0. I don't think we realized there was a 3.4.1 version. We'll need to see what the differences are between them.
The Webpack version produces a javascript framework agnostic version. It's more for the bundling aspect and making it into an npm dependency.

**Comment by bignamehere** [comment]
@francisrupert @arosenblum  @atdiff  

I was able to update the datepicker2 feature branch with working JS that built the structure of the Search component. It is now looking closer to an FSA Style component. I need to look at why the keyboard listeners are not working, but if you have time, feel free to diagnose that as well. :)

take a look b4c0122

**Comment by francisrupert** [comment]
**Initial Styling Status, FYI only**

To experiment, I've played around with the `spa-reference-app-ui` instance of the Date Picker purely as a way to backwards-engineer it and play around with its style: **screenshot below**. This is by _no means_ the UI I have in mind, though it's at least presents better than what the Reference App had going before. To be clear the SCSS I did is atrocious, but it told me a lot.

The outcome I'm aiming for is as an exercise in _forming an opinion_ for how the UX team can customize it: e.g. how much of the dynamic markup should change / be replaced / removed / edited / etc; do we namespace it; and so on. I'll continue to do so carefully -- _particularly_ without putting the JS at risk.

Feel free to checkout [my working branch](http://52.61.117.207/projects/SPAI/repos/spa-reference-app-ui/browse?at=feature/ux-aesthetic-tweaks) and [commits](http://52.61.117.207/projects/SPAI/repos/spa-reference-app-ui/commits/88195a1fbbef0e3d8ecc3f6d86283282d3e8f0c4) to see it in action. 

![localhost_9000_spa-reference-app_inspections_new](https://user-images.githubusercontent.com/1165933/57404303-469edb00-71a1-11e9-8d5d-d404396e37e5.png)

![image](https://user-images.githubusercontent.com/1165933/57404278-37b82880-71a1-11e9-9e7d-a512d95dfeae.png)

**Comment by bignamehere** [comment]
@francisrupert this Issue is getting a bit convoluted, and we should probably break out Project specific tasks into the Git Issues related to the repo/project, and we can track those tasks in the Project view of FSA Style. Tasks like "Ensure it works sans-Webpack (tech stack-agnostic)" are not at all related to the Prototype Kit, because it is highly dependent on Webpack by design.

So let's start breaking up the individual Tasks into separate Issues within a Repo/Project. We can refer back to this Issue as reference.

**Comment by francisrupert** [comment]
@bignamehere,

Correct. I'd already proceeded this morning with exploration as a branch on `fsa-style` repo (haven't committed yet). The work I'd done on the SPA Ref App (cited in this https://github.com/USDA-FSA/fsa-prototype-kit/issues/15#issuecomment-490874494) was two part: 1) get the SPA Ref App example less broken, and 2) familiarize myself with it and form approach.

Once I've hit a certain point, we'll connect and break this down even further to specific tasks. Meanwhile, the adjustments you made up to commit b4c0122 are pretty insane, and very helpful for me.

**Comment by bignamehere** [comment]
As an update to the project, I added the capability to control if the component uses just an icon or the standard "Calendar" button. It is implemented as an option based as `useIcon: "true"` in the JavaScript. We could explore passing in the buttons class value instead, but that opens up the ability to directly pass in a string, which probably is no bueno. We can discuss any other tweaks needed to better match with the FSA Style methodology. 

63fd988

**Comment by bignamehere** [comment]
Closing this issue as it is related to a different code implementation and methodology that what was implemented and released.
