### ISSUE TITLE
Contain fonts and img to src

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-prototype-kit#17]
Source `fonts` and `img` are incorrectly getting Webpacked to root of project, rather than in `src`, presumably as a result of #16 (https://github.com/USDA-FSA/fsa-prototype-kit/commit/c3d753a8a3ba4ca1a9e52a93f03a13b918609a36#diff-5c572bb8f24a00a84aa28f22d3a39ba5)

### Current 
```
fsa-prototype-kit
├── src/
├── img/
├── fonts/
├── webpack.etc.js
└── etc.ext
```
### Expected
```
fsa-prototype-kit
├── src/
│   ├── fonts/
│   ├── img/
│   └── etc/
├── webpack.etc.js
└── etc.ext
```

**Comment by bignamehere** [comment]
"Webpacking" the img and fonts directories to the root was intentional, as the way the webpack.common.js config and specifically the file-loader, required these directories to match the "outputPath" option. After doing some research it appears that using a publicPath option for the file-loader allows us to achieve the following:

- copy img and font files from fsa-style node_modules into dist
- file-loader now tells webpack to use "../fonts/" (and img) as directory structure as opposed to "..src/fonts" or "../dist/fonts"
- file-loader takes inline img and font assets and allows Handlebars to interpret them and their paths correctly

Even though the file-loader copies the interpreted files to the dist directory, both the CopyWebpackPlugin and file-loader are required to pull in the assets from Handlebars HTML code and also assets from the SCSS.

One benefit of this solution is that the source files from fsa-style node_modules never are actually placed into the src directory and tracked via Github. They are also "sourced" from the fsa-style within node_modules.

It seems to be working correctly, so I will close on commit.

**Comment by bignamehere** [comment]
Found a bug while testing...

It appears that if a User places an image or font in the src directory to be used in their application, webpack does not include it into the dist output. The fix I did was to add the font and img directory from src into the CopyWebpackPlugin array.

This has fixed the issue, but there might be a more elegant solution that needs to be explored.

**Comment by francisrupert** [comment]
@bignamehere,

Outstanding. I've tested and confirmed it works, **however**... I'm a tad confused about when images go _from_ `src` _to_ `dist`.

### Currently

1. I place a new image in `/src/img/`
1. No watch response observed
1. I reference it, `<img src="../img/file.jpg">`
1. It _does_ appear at [http://localhost:8888/](http://localhost:8888/), though I understand that's because they're being served up from `/src/img/` rather than `/dist/img/`

### Expected

1. I place a new image in `/src/img/` (or _modify_ existing one)
1. `watch` responds by copying from `/src/img/` to `/dist/img/`
1. I reference it, `<img src="../img/file.jpg">`
1. Image is served up from `/dist/img/`

### Asking

For **Step 4** in each of above, what's the correct approach? I did confirm that canceling `start` and rerunning `build` that `/src/file.jpg` gets copied to `/src/file.jpg`. So it eventually gets there, and I'm not sure this current approach is strictly wrong -- though feels weird to me.

**Comment by francisrupert** [comment]
@bignamehere,

Um did we just say the same thing?

**Comment by bignamehere** [comment]
@francisrupert  Yeah, basically.

The fix I implemented seems to work when you start from a `build` then do a `start`... but not sure if webpack "watches" and runs the CopyWebpackPlugin. That might only run with a `build`.

Testing now.

**Comment by bignamehere** [comment]
It looks like `watch` is working fine to dynamically reload the project if a user places an asset in the img or font directory, it will work fine, but it will not automatically run the CopyWebpackPlugin plugin. You need to perform a `build` to have the asset(s) placed in the proper directory in dist, and for the CSS to properly reference it. 

Always perform a `build` before you push dist to a dev site.

closing as per c15bcb53fbd061ee0b2716a6e9d901619d53faf9
